### ISSUE TITLE
Support for MinGW builds?

### ISSUE THREAD

**Issue by piponazo** [huangqinjin/wmain#1]
Hi. First of all, thanks for this wonderful project. It helped me to learn few things!

I am applying the lessons learned here to the Exiv2 project:
https://github.com/Exiv2/exiv2/pull/2090

However I have encountered problems to make this work on MSYS2/MinGW builds. I tried to compile your project with MSYS2 & MinGW and the **utf8_echo** apps also have problems to print properly greek characters:

![image](https://user-images.githubusercontent.com/102645/153625328-43199c62-cc72-41cc-afd2-2594e97e98e0.png)

Do you have any idea of how to deal with UTF-8 and MinGW?

**Comment by piponazo** [comment]
I finally found out how to deal with the MinGW builds. In case you are interested, I can create a PR to add support for MinGW builds to your project. Please, let me know.

**Comment by huangqinjin** [comment]
@piponazo Thanks for your interest in this repo. 

I believe to get **utf8_echo** work with MinGW gcc, `-municode` option is needed to pick up `wmain` as the program entry. Because gcc does not understand the MSVC option `/ENTRY:` .

I am actually not interested in MinGW builds, as the repo is just to demonstrate the mechanism and concepts of UTF-8 and UCRT.

What I am interested in is, how to make MinGW link to UCRT instead of MSVCRT? With UCRT and UFT-8 locale, you can pass UTF-8 strings to C APIs like `fopen`. Do you have any sharings?

**Comment by piponazo** [comment]
Hi @huangqinjin , you can find it how I enabled MinGW builds in Github to link against UCRT:
https://github.com/Exiv2/exiv2/pull/2090

The trick is to use the proper MinGW environment for that. When you use MSYS2, you can use different shortcuts to use different environments and one of them is the UCRT one. I also left some instructions in the previous PR about those things.

**Comment by huangqinjin** [comment]
Really nice to know that MSYS2 now provides UCRT64 environment officially! At the time I wrote this repo, I could only found that a custom build of MinGW is needed.

**Comment by huangqinjin** [comment]
Thanks for your information @piponazo . I have added MinGW support.
